export const TYPES = {
	ADD_TASK: "ADD",
	FILTERED_TASK: "FILTERED_TASK",
	UPDATE_TASK: "UPDATE_TASK",
	COMPLETED_TASK: "CHECKED_TASK",
	DELETE_TASK: "DELETE_TASK",
	RESET_FILTERED_TASK: "RESET_FILTERED_TASK",
	UPDATE_DATA_TASK: "UPDATE_TASK_TAG",
};
